[package]
name = "worldgen"
description = "Noisemap and world generation library"
version = "0.1.0"
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]
license = "Apache-2.0"
build = "build.rs"

[dependencies]
libc = "0.1.8"

[build-dependencies]
gcc = "0.3.8"
