[package]
name = "worldgen"
description = "Noisemap and world generation library"
version = "0.1.2"
readme = "README.md"
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]
repository = "https://github.com/YeyaSwizaw/rust-worldgen"
documentation = "http://www.samuelsleight.co.uk/rust-docs/worldgen"
license = "Apache-2.0"
build = "build.rs"

[dependencies]
libc = "0.1.8"

[build-dependencies]
gcc = "0.3.8"
